module.exports = {
	dest: '/docs',
	src: 'src/',
	base: '/',
	description: 'Smartlook documentation',
	menu: [
		{
			name: 'Web',
			menu: [
				'Getting started',
				'Identify visitor',
				'Consent and sensitive data',
				'Sensitive data protection',
				'Custom events',
				'Custom event properties',
				'Custom click properties',
				'Custom navigation event',
				'Recording API',
				'Error logging',
			],
		},
		{
			name: 'SDK Installation',
			menu: [
				'Android',
				'iOS',
				'Cocos',
				'Cordova',
				'Flutter',
				'Ionic',
				'React Native',
				'Unity',
				'Unreal Engine 4',
				'Xamarin',
			],
		},
		{
			name: 'SDK Conceptual',
			menu: [
				'SDK Installation',
				'Setup & Start Recording',
				'When The Recordings Appear in Dashboard?',
				'Life Cycle, Session, User',
				'What is recorded and how',
				'Handling Sensitive Data',
				'Screen Recording Quality',
				'Event Tracking',
				'Recording Navigation',
				'Integrating with Other Tools',
			],
		},
		'SDK API reference',
		'SDK Cookbooks',
		'SDK Integrations',
		{
			name: 'REST API',
			menu: ['Overview', 'Cookbook', 'API Reference'],
		},
		{
			name: 'WEBHOOKS',
			menu: ['Overview'],
		},
	],
	title: 'Smartlook',
}
